import createClient from 'openapi-fetch'
import { type paths } from '@johannes-lindgren/openapi' // generated by openapi-typescript

type Story =
  paths['/v1/spaces/{space_id}/stories/']['get']['responses']['200']['content']['application/json']['stories']

const client = createClient<paths>({ baseUrl: 'https://mapi.storyblok.com/' })

const { data } = await client.GET('/v1/spaces/{space_id}/stories/', {
  params: {
    path: {
      space_id: 1234,
    },
  },
})
