openapi: 3.1.0
info:
  title: Storyblok Management API
  description: Storyblok's Management API allows you to manage your content programmatically.
paths:
  /v1/spaces/{space_id}/stories/:
    get:
  #      $ref: './v1/spaces/stories/get.yml'
  $ref: './v1/spaces/discussions/comments/index.yml#/paths'
#  $ref: './v1/spaces/discussions/comments/mark_as_read/index.yml#/paths'
